spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, verification, swagger"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lemon_db:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: cos1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create